services:
  app:
    image: ghcr.io/gtarraga/papers-reading-club:latest
    container_name: papers-reading-club
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"
    env_file:
      - .env.production
    volumes:
      - ./data/data:/app/data
      - ./data/logs:/app/logs
