services:
  app:
    image: ghcr.io/gtarraga/papers-reading-club:latest
    container_name: papers-reading-club
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      # Seed script variables (only needed for initial database seeding)
      - TOKEN_PATTERN=${TOKEN_PATTERN:-}
      - INITIAL_TOKEN=${INITIAL_TOKEN:-}
      - INITIAL_FIRST_NAME=${INITIAL_FIRST_NAME:-}
      - INITIAL_LAST_NAME=${INITIAL_LAST_NAME:-}
    env_file:
      - .env.production
    volumes:
      - ./data/data:/app/data
      - ./data/logs:/app/logs
